import Head from 'next/head'

const Meta = () => {
  return (
    <div>
      <Head>
        <title>Modal Card Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Meta
